---
- hosts: HQCluster
  connection: local
  gather_facts: no
  vars_prompt:
    - name: dn
      prompt: Enter the directory number to create
      private: no
    - name: partition
      prompt: Enter the route partition
      private: no
  tasks:
    - name: Add Line
      uri:
        url: "https://{{ ansible_host }}:8443/axl/"
        method: POST
        headers:
          Content-Type: text/xml
          SOAPAction: '"CUCM:DB ver=14.0 addLine"'
        force_basic_auth: yes
        user: "{{ hostvars[ansible_host].axl_user }}"
        password: "{{ hostvars[ansible_host].axl_password }}"
        body_format: raw
        body: '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/14.0">
                  <soapenv:Header/>
                  <soapenv:Body>
                      <ns:addLine sequence="?">
                        <line>
                            <pattern>{{ dn }}</pattern>
                            <routePartitionName>{{ partition }}</routePartitionName>
                        </line>
                      </ns:addLine>
                  </soapenv:Body>
               </soapenv:Envelope>'
        validate_certs: false
        return_content: yes
        status_code: 200

