---
- hosts: HQCluster
  connection: local
  gather_facts: no
  vars_prompt:
  - name: userid
    prompt: Enter the User Id of the user to create
    private: no
  - name: lastname
    prompt: Enter the user last name
    private: no
  - name: password
    prompt: Enter the user password
    private: yes
  tasks:
    - name: Add end user
      uri:
        url: "https://{{ ansible_host }}:8443/axl/"
        method: POST
        headers:
          Content-Type: text/xml
          SOAPAction: '"CUCM:DB ver=14.0 addUser"'
        force_basic_auth: yes
        user: "{{ hostvars[inventory_hostname].axl_user }}"
        password: "{{ hostvars[inventory_hostname].axl_password }}"
        body_format: raw
        body: '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/12.5">
                <soapenv:Header/>
                <soapenv:Body>
                    <ns:addUser sequence="1">
                      <user>
                          <lastName>{{ lastname }}</lastName>
                          <userid>{{ userid }}</userid>
                          <password>{{ password }}</password>
                      </user>
                    </ns:addUser>
                </soapenv:Body>
              </soapenv:Envelope>'
        validate_certs: false
        return_content: yes
        status_code: 200
