---
- name: AXL CUCM Version
  hosts: HQCluster
  connection: local
  gather_facts: false
  tasks:
    - name: Get CUCM version (active partition)
      ansible.builtin.include_tasks: axl/getCCMVersion.yml
