---
- name: AXL Add Phone
  hosts: HQCluster
  connection: local
  gather_facts: false

  vars_prompt:
    - name: device_name
      prompt: Enter device name (e.g. SEP123456789012)
      private: false
    - name: model
      prompt: Enter device model (e.g. Cisco 7975)
      private: false
    - name: dn
      prompt: Enter the line directory number (e.g. 1001)
      private: false
    - name: routepartition
      prompt: Enter the line partition (press enter for none)
      private: false

  tasks:
    - name: Get CUCM version
      ansible.builtin.include_tasks: axl/getCCMVersion.yml

    - name: Add the new phone
      ansible.builtin.include_tasks: axl/addPhone.yml
