---
- hosts: publisher
  connection: local
  gather_facts: no
  vars_prompt:
    - name: userid
      prompt: Enter userid
      private: no
    - name: lastName
      prompt: Enter last name
      private: no
    - name: password
      prompt: Enter password
      private: no
    - name: pin
      prompt: Enter user PIN (numbers only)
      private: no
    - name: device_name
      prompt: Enter the user's device name (e.g. SEP123456789012)
      private: no

  tasks:
    - name: Get CUCM version
      include_tasks: axl/getCCMVersion.yml

    - name: Add the new user
      include_tasks: axl/addUser.yml
      