---
  # Run with command line params: 
  #   ansible-playbook axl_service_parameter.yml -e "service='Cisco CallManager' parameter_name=HoldReversionDuration"

- hosts: HQCluster
  connection: local
  gather_facts: no

  vars_prompt:
  - name: service
    prompt: "Enter the service name (e.g.: Cisco CallManager)"
    private: no
  - name: parameter_name
    prompt: "Enter the service parameter name (e.g.: HoldReversionDuration)"
    private: no

  tasks:
    - name: Get CUCM version
      include_tasks: axl/getCCMVersion.yml

    - name: getServiceParameter.yml
      include_tasks: axl/getServiceParameter.yml