---
- name: AXL SQL Query
  hosts: HQCluster
  connection: local
  gather_facts: false

  vars_prompt:
    - name: sql
      prompt: Enter the SQL query to execute
      private: false

  tasks:
    - name: Get CUCM version
      ansible.builtin.include_tasks: axl/getCCMVersion.yml

    - name: Execute SQL Query
      ansible.builtin.include_tasks: axl/executeSQLQuery.yml

    - name: Convert to csv and write to file
      ansible.builtin.copy:
        mode: 0644
        content: "{{ rows | axlquery2csv }}"
        dest: "QUERY_RESULTS.csv"
