---
- name: AXL Add Line
  hosts: HQCluster
  connection: local
  gather_facts: false

  vars_prompt:
    - name: dn
      prompt: Enter new directory number (e.g. 1001)
      private: false
    - name: routepartition
      prompt: Enter the partition name (press enter for none)
      private: false

  tasks:
    - name: Get CUCM version
      ansible.builtin.include_tasks: axl/getCCMVersion.yml

    - name: Add a new line
      ansible.builtin.include_tasks: axl/addLine.yml
