---
- name: AXL Bulk Add Users
  hosts: HQCluster
  connection: local
  gather_facts: false

  tasks:
    - name: Read CSV data
      community.general.read_csv:
        path: USER_DATA.csv
      register: csv_data

    - name: Add bulk users
      vars:
        dn: "{{ item.dn }}"
        routepartition: "{{ item.routepartition }}"
        device_name: "{{ item.device_name }}"
        model: "{{ item.model }}"
        userid: "{{ item.userid }}"
        lastname: "{{ item.lastname }}"
        password: "{{ item.password }}"
        pin: "{{ item.pin }}"
      ansible.builtin.include_tasks: axl/addLinePhoneUser.yml
      loop: "{{ csv_data.list }}"
