---
- name: AXL Add Line/Phone/User
  hosts: HQCluster
  connection: local
  gather_facts: false

  vars_prompt:
    - name: userid
      prompt: Enter userid
      private: false
    - name: lastname
      prompt: Enter last name
      private: false
    - name: password
      prompt: Enter password
      private: false
    - name: pin
      prompt: Enter user PIN (numbers only)
      private: false
    - name: device_name
      prompt: Enter the user's device name (e.g. SEP123456789012)
      private: false
    - name: model
      prompt: Enter the device model (e.g. Cisco 7975)
      private: false
    - name: dn
      prompt: Enter new directory number (e.g. 1001)
      private: false
    - name: routepartition
      prompt: Enter the partition name (press enter for false partition)
      private: false

  tasks:
    - name: Get CUCM/AXL versions
      ansible.builtin.include_tasks: axl/getCCMVersion.yml

    - name: Add new line
      ansible.builtin.include_tasks: axl/addLine.yml

    - name: Add new phone
      ansible.builtin.include_tasks: axl/addPhone.yml

    - name: Add new user
      ansible.builtin.include_tasks: axl/addUser.yml
