---
- hosts: HQCluster
  connection: local
  gather_facts: no

  tasks:
    - name: Execute CLI command
      cisco_vos_cli:
        cli_address: "{{ ansible_host }}"
        cli_user: "{{ hostvars[ansible_host].cli_user }}"
        cli_password: "{{ hostvars[ansible_host].cli_password }}"
        cli_command: show myself
        cli_responses:
          - expect: "admin:"
            response: utils snmp config mib2 list
            timeout: 10
          - expect: "admin:"
            response: utils snmp config 1/2c community-string list
            timeout: 10
          - expect: "admin:"
            response: utils snmp config 1/2c inform list
            timeout: 10
          - expect: "admin:"
            response: utils snmp config 1/2c trap list
            timeout: 10

      register: response

    - debug: 
        msg: |
          Raw: {{ response.output['raw'] }}
          Tokenized: {{ response.output['tokenized'] | to_nice_json }}

    