---
- name: CLI Show Version
  hosts: HQCluster
  connection: local
  gather_facts: false

  tasks:
    - name: Execute CLI command
      cisco_vos_cli:
        cli_address: "{{ ansible_host }}"
        cli_user: "{{ hostvars[ansible_host].cli_user }}"
        cli_password: "{{ hostvars[ansible_host].cli_password }}"
        cli_command: show version active
      register: response

    - name: Debug
      ansible.builtin.debug:
        msg: |
          Raw: {{ response.output['raw'] }}
          Tokenized: {{ response.output['tokenized'] | to_nice_json }}
          Active version: {{ response.output['tokenized'][0][3] }}
