---
- hosts: HQCluster
  connection: local
  gather_facts: no
  tasks:
    - name: Get CUCM version (active partition)
      uri:
        url: "https://{{ ansible_host }}:8443/axl/"
        method: POST
        headers:
          Content-Type: text/xml
          SOAPAction: '"CUCM:DB ver=14.0 getCCMVersion"'
        force_basic_auth: yes
        user: "{{ axl_user }}"
        password: "{{ axl_password }}"
        body_format: raw
        body: '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/14.0">
                <soapenv:Header/>
                <soapenv:Body>
                  <ns:getCCMVersion>
                    <processNodeName/>
                  </ns:getCCMVersion>
                </soapenv:Body>
              </soapenv:Envelope>'
        validate_certs: false
        return_content: yes
        status_code: 200
      register: response

    - name: Parse CUCM version from response
      xml:
          xmlstring: "{{ response.content }}"
          namespaces:
            soapenv: http://schemas.xmlsoap.org/soap/envelope/
            ns: http://www.cisco.com/AXL/API/14.0
          xpath: /soapenv:Envelope/soapenv:Body/ns:getCCMVersionResponse/return/componentVersion/version
          content: text
      register: cucm_version
      delegate_to: localhost

    - debug:
        msg: "CUCM version: {{ cucm_version.matches[0].version }}"