---
- name: Webex Get Licenses
  hosts: WebexOrgs
  connection: local
  gather_facts: false

  tasks:
    - name: Retrieve license counts
      vars:
        secret: "secret=oauthapp/creds/{{ credential }} token={{ lookup('env', 'VAULT_TOKEN') }} url={{ lookup('env', 'VAULT_ADDR') }}"
        credentials: "{{ lookup('hashi_vault', secret) }}"
        webex_token: "{{ credentials | json_query('access_token') }}"
      ansible.builtin.uri:
        url: "https://webexapis.com/v1/licenses?{{ org_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ webex_token }}"
        return_content: true
        status_code:
          - 200
      register: response

    - name: Delete output file if present
      ansible.builtin.file:
        state: absent
        path: LICENSE_REPORT.txt

    - name: Output data to file
      ansible.builtin.lineinfile:
        mode: 0644
        create: true
        path: LICENSE_REPORT.txt
        line: "{{ item[0] }}: {{ item[1] }}"
      loop: "{{ response.json | json_query('items[*].[name,totalUnits]') }}"
      no_log: true
