---
- hosts: HQCluster
  connection: local
  gather_facts: no
  tasks:
    - name: Read CSV data
      read_csv:
        path: addLinePhoneUserLoop.csv
      register: csv_data
    - name: Add all lines
      include_tasks: subtasks/addLine.yml
      loop: "{{ csv_data.list }}"
    - name: Add all phones, associating their lines
      include_tasks: subtasks/addPhoneLine.yml
      loop: "{{ csv_data.list }}"
    - name: Add all users, associating their phones
      include_tasks: subtasks/addUserPhone.yml
      loop: "{{ csv_data.list }}"